name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'   # 仅匹配如 0.0.1、1.2.3 等 tag

permissions:
  contents: write  # 关键！必须有

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Get Tag Name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF##refs/tags/}" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          mkdir -p build
          BIN_NAME="toolbox-${TAG_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/${BIN_NAME}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: build/toolbox-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}